plugins { id 'com.android.application' }

android {
    namespace 'com.godnit.terrainstudio.three'
    compileSdk 36

    defaultConfig {
        applicationId 'com.godnit.terrainstudio.three'
        minSdk 21
        targetSdk 34
        versionCode 14
        versionName '1.4-v14'
    }

    signingConfigs {
        releaseLike {
            storeFile file('terrain-debug.keystore')
            storePassword 'terrainstudio'
            keyAlias 'terrain'
            keyPassword 'terrainstudio'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.releaseLike
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
